name: Test CI/CD Pipeline

on:
  push:
    branches:
      - dev
env:
  DOCKER_IMAGE: blessedsoft/linker-app  # Replace with your Docker Hub username and image name
  DOCKER_TAG: ${{ github.sha }}  # Use commit SHA as tag

jobs:
  build-scan-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          scan-ref: '${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run tests
        run: |
          # Assuming tests are run via Docker Compose or a script
          docker-compose up -d  # Start services if needed


      - name: Push Docker image to Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          docker tag ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} ${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ env.DOCKER_IMAGE }}:latest